services:
  client:
    build:
      context: ./client
      image: sanicdogg/microservices-testing-client:latest
    ports:
      - "80:80"
  server:
    build:
      context: ./server
      image: sanicdogg/microservices-testing-server:latest
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tests:/app/artillery-volume
volumes:
  tests:
