services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tests:/app/artillery-volume
    depends_on:
      - client
volumes:
  tests: