name: Docker Compose Actions

on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build and run with docker-compose
      run: |
        docker-compose up -d --build
        docker-compose ps

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag the Docker image
      run: docker tag microservices-testing:latest sanicdogg/microservices-testing:latest

    - name: Push the Docker image to DockerHub
      run: docker push sanicdogg/microservices-testing:latest
